# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-03 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfluxMigration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_host', models.CharField(default='localhost', max_length=128)),
                ('source_port', models.PositiveIntegerField(default=8086)),
                ('source_db', models.CharField(default='default', max_length=128)),
                ('source_measurement', models.CharField(default='default', max_length=128)),
                ('destination_host', models.CharField(default='localhost', max_length=128)),
                ('destination_port', models.PositiveIntegerField(default=8086)),
                ('destination_db', models.CharField(default='default_dest', max_length=128)),
                ('destination_measurement', models.CharField(default='default', max_length=128)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('slot_seconds', models.PositiveIntegerField(default=300)),
                ('translation_yaml', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MigrationSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('confirmed_success', models.DateTimeField(blank=True, default=None, null=True)),
                ('migration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='influx_migrations.InfluxMigration')),
            ],
        ),
    ]
